GET http://localhost:8080/api/courses
###

GET http://localhost:8080/api/courses/2
###

POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "name": "Nodejs",
  "category": "Back-end",
  "lessons": [{
    "name": "introdução",
    "youtubeUrl": "1234567890"
  }]
}
###

PUT http://localhost:8080/api/courses/2
Content-Type: application/json

{
  "name": "Node",
  "category": "Back-end"
}
###

DELETE http://localhost:8080/api/courses/2