GET http://localhost:8080/api/courses

###
GET http://localhost:8080/api/courses?page=0&pageSize=100
###

GET http://localhost:8080/api/courses/2
###

POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "name": "Angular",
    "category": "Front-end",
    "lessons": [
        {
          "name": "Introdução",
          "youtubeUrl": "tPOMG0D57S0"
        },
        {
          "name": "Introdução2",
          "youtubeUrl": "tPOMG0D57S0"
        }
    ]
}
###

PUT http://localhost:8080/api/courses/2
Content-Type: application/json

{
  "name": "Node",
  "category": "Back-end"
}
###

DELETE http://localhost:8080/api/courses/2